### ISSUE TITLE
SMTP relay

### ISSUE THREAD

**Issue by azlux** [traduora/traduora#140]
**Describe the bug**
Hi, I have a personnal smtp relay, traduora isn't able to send email with it because the STMP TLS is secured by a STARTSSL self signed certificate

**To Reproduce**
Install  with docker/environment variable. Set email to a personal smtp relay

** Environment :**
 - Version 0.16.0

**Debug logs**
```
172.18.0.100 - POST /api/v1/auth/forgot-password HTTP/1.1 200 - - 320.640 ms
(node:1) UnhandledPromiseRejectionWarning: Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by azlux** [comment]
If it's help, here is my docker-compose:
```
    smtp-relay:
        image: panubo/postfix
        container_name: smtp_relay
        hostname: smtp_relay
        restart: on-failure
        environment:
            MAILNAME: ${EMAIL_SMTP_DOMAIN}
            RELAYHOST: "[${EMAIL_SMTP_SERVER}]:${EMAIL_SMTP_PORT}"
            RELAYHOST_PASSWORDMAP: "[${EMAIL_SMTP_SERVER}]:${EMAIL_SMTP_PORT}:${EMAIL_SMTP_USER}:${EMAIL_SMTP_PASSWORD}"
            POSTFIX_ADD_MISSING_HEADERS: "yes"
            RELAYHOST_AUTH: "yes"
            MYNETWORKS: 172.18.0.0/16, [fd00::]/64

    traduora:
        image: traduora/traduora
        container_name: traduora
        hostname: traduora
        expose:
            - 8080
        environment:
            TR_VIRTUAL_HOST: <my-personnal-domain>
            TR_DB_HOST: mariadb
            TR_DB_DATABASE: ${TRADUORA_DB_DATABASE}
            TR_DB_USER: ${TRADUORA_DB_USER}
            TR_DB_PASSWORD: ${TRADUORA_DB_PASSWORD}
            TR_MAIL_SENDER: ${EMAIL_SMTP_USER}
            TR_MAIL_HOST: smtp-relay
            TR_MAIL_PORT: 25
            TR_MAIL_USER: ""
            TR_MAIL_PASSWORD: ""
            TR_SECRET: <my-personnal-sercret>
            TR_SIGNUPS_ENABLED: 'true'
            TR_MAIL_SECURE: 'true'
            TR_MAIL_DEBUG: 'true'
            NODE_TLS_REJECT_UNAUTHORIZED: 0 # this is a try
            TZ: Europe/Paris
        depends_on:
            - mariadb
```
