### ISSUE TITLE
"ER_TOO_LONG_KEY" causes crash when starting container

### ISSUE THREAD

**Issue by OfficialCRUGG** [traduora/traduora#85]
Hey there! I'm currently setting up Traduora as my first docker application and set up a start command with all important envroinment variables it doesn't work, when I look at the logs of the docker container, there is an error after "Running DB migrations if necessary":
```
(node:1) UnhandledPromiseRejectionWarning: QueryFailedError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
    at new QueryFailedError (/opt/traduora/node_modules/typeorm/error/QueryFailedError.js:11:28)
    at Query.<anonymous> (/opt/traduora/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:169:45)
    at Query.<anonymous> (/opt/traduora/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/opt/traduora/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/opt/traduora/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/opt/traduora/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/opt/traduora/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/opt/traduora/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/opt/traduora/node_modules/mysql/lib/protocol/Protocol.js:38:16)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
So I looked if I could find any issue about this, but there seems to be nobody having this problem. Does anyone know what causes this? I see that something is too long, but I don't know what key is talked about in this error.

**Comment by OfficialCRUGG** [comment]
I'm now using docker-compose but this issue still occurs. Here is my config:
```yaml
version: '3'
services:
  traduora:
    image: traduora/traduora:latest
    ports:
     - "9295:9295"
    environment:
      TR_DB_HOST: <host>
      TR_DB_USER: traduora
      TR_DB_DATABASE: traduora
      TR_DB_PASSWORD: <password>
      TR_DB_PORT: 3306
      TR_VIRTUAL_HOST: translate.example.net
      NODE_ENV: production
      TR_PORT: 9295
```
