### ISSUE TITLE
How to deploy under NGINX subpath

### ISSUE THREAD

**Issue by d4rth-v4d3r** [traduora/traduora#92]
Currently I have this configuration in my nginx.conf file
```
#configuration for my-domain
location /company {
            location ~ /traduora {
			rewrite                                /traduora/(.*)$ /$1 break;
			proxy_pass                             http://traduora:8080;
			proxy_redirect                         http://traduora:8080/ $scheme://$host/traduora/;
			proxy_set_header Host $host;
			proxy_set_header Upgrade			$http_upgrade;
			proxy_set_header Connection 		"upgrade";
			proxy_set_header Host				$host;
			proxy_set_header X-Real-IP			$remote_addr;
			proxy_set_header X-Forwarded-For	$proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto	$scheme;
			proxy_set_header X-Forwarded-Host	$host;
			proxy_set_header X-Forwarded-Port	$server_port;
			proxy_http_version 1.1;
			proxy_cache_bypass $http_upgrade;
			client_max_body_size 20M;
		}
}
```
I deployed standard docker image, using this configuration:

```
mysqldb:
    image: mysql:5.7
    container_name: "mysqldb"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=tr_dev
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - "/storage/mysql/traduora:/var/lib/mysql"
    networks:
      - apps
      - platforms
  traduora:
    image: traduora/traduora:latest
    container_name: "traduora"
    ports:
      - "8080:8080"
    environment:
      - TR_VIRTUAL_HOST=http://my-domain:10443/company/traduora/
      - TR_DB_HOST=mysqldb
    networks:
      - apps
      - platforms
    depends_on:
      - mysqldb
```

But I can't make it work. It gives me 404 while trying to load .js resources from app. What can I do?

Should I need to build a custom image from source? What changes do I need to do to make this work?

I tried to edit webapp/src/index.html  to add base href and built a custom image, but api did not work (returned 404)
